class BotGround::HTTPRequest
  attr_reader headers: Hash[String, String]
  attr_reader body: String
  def initialize: (?headers: Hash[String, String], ?body: String) -> void
end

class BotGround::Worker
  include Sidekiq::Worker
  extend Sidekiq::Worker::ClassMethods

  extend BotGround::_ServerConfig
  extend BotGround::_ClientConfig

  self.@client: BotGround::Client
  self.@signing_secret: String?

  def self.configure_server: () { (BotGround::_ServerConfig) -> void } -> void
  def self.configure_client: () { (BotGround::_ClientConfig) -> void } -> void

  def self.client: () -> BotGround::Client

  def self.handlers: () -> Array[BotGround::_Handler]
  def self.enqueue: (BotGround::HTTPRequest req, ?verify: bool) -> {:type => String, value: untyped}
  def perform: (String channel, String user, String text) -> void

  private

  def find_router: (String) -> (nil | BotGround::Router)
  def self.get_event_info: (untyped) -> [String, String, String]
end

interface BotGround::_ServerConfig
  def client=: (BotGround::Client) -> void
end

interface BotGround::_ClientConfig
  def signing_secret=: (String?) -> void
end
