class BotGround::Worker
  include Sidekiq::Worker
  extend Sidekiq::Worker::ClassMethods

  self.@client: BotGround::Client

  def self.handlers: () -> Array[BotGround::_Handler]
  def self.configure: () { (self) -> void } -> void
  def self.client: () -> BotGround::Client
  def self.client=: (BotGround::Client) -> void
  def self.enqueue: (Net::HttpRequest req, ?verify: bool) -> {:type => String, value: untyped}
  def perform: (String channel, String user, String text) -> void

  private

  def find_router: (String) -> (nil | BotGround::Router)
  def self.get_event_info: (untyped) -> [String, String, String]
end
