source "https://rubygems.org"

gem "botground", path: "../"
gem "sinatra", ">= 2.0"
gem "sidekiq", ">= 6.0"
gem "dotenv", ">= 2.7"
gem "minitest", ">= 5.14.2"
gem "puma", ">= 5.5.1"

group :development do
  gem "steep", "0.47.0"
  gem "activesupport", "~> 6.0" # for https://github.com/soutaro/steep/issues/466
end
