target :app do
  signature "sig", "assets/sig"

  check "worker.rb"
  check "config.ru"

  library "botground"

  library "logger" # for sidekiq
  library "monitor" # for logger

  repo_path "../vendor/rbs/gem_rbs_collection/gems"
  library "rack", "sidekiq"
  library "redis" # for sidekiq

  repo_path "../assets/rbs/gems"
  library "sinatra", "slack"
end
