module Sidekiq
  def self.configure_server: () { (Sidekiq::Config) -> void } -> void
  def self.configure_client: () { (Sidekiq::Config) -> void } -> void
end

module Sidekiq::Config
  attr_accessor redis: { db: Integer }
end

module Sidekiq::Worker
  def logger: () -> Sidekiq::Logger
end

module Sidekiq::Worker::ClassMethods
  def perform_async: (*untyped) -> Integer
end

class Sidekiq::Logger < Object
  def debug: (String) -> void
  def info: (String) -> void
  def warn: (String) -> void
  def error: (String) -> void
  def fatal: (String) -> void
end