class Slack
  def self.configure: () { (self) -> void } -> void
  def self.token=: (String) -> void
end

module Slack::Web
end

class Slack::Web::Client < Object
  def chat_postMessage: (channel: String, text: String) -> void
end

module Slack::Events
end

class Slack::Events::Request < Object
  def initialize: (Net::HttpRequest, ?signing_secret: String?) -> void
  def body: () -> String
  def valid?: () -> bool
end
